### ISSUE TITLE
Error : undefined is not a function

### ISSUE THREAD

**Issue by prasadbcs** [dvonlehman/is-ec2#1]
I'm using this module, and getting the following error on ec2 linux instance
/home/centos/test/node_modules/is-ec2/index.js:8
  return exec(command).toString().trim() === 'ec2';
         ^
TypeError: undefined is not a function
    at module.exports (/home/centos/test/node_modules/is-ec2/index.js:8:10)
    at Object.<anonymous> (/home/centos/test/index.js:6:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by dvonlehman** [comment]
My best guess is that your version of node does not support the `child_process.execSync` function which was introduced in node v0.11.12.

https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

Any chance this is the case?
